'use client'
import nodes from '../components/data'
import React from 'react';

const Datas = [
    {
      nation: 'USA',
      data: [
        {
          population: 35485000,
          percentageofworld: 4.2,
          date: "9 Oct 2023",
          source: 'National annual projection',
          fullname: "United States of America",
          motto: "In God We Trust",
          anthem: "The Star-Spangled Banner",
          capital: "Washington, D.C",
          largestcity: "New York City",
          officiallanguages: "none at the federal level",
          nationallanguage: "English",
          flag: 'flag',
          demonym: "American",
          government: "Federal presidential constitutional republic",
          president: "Joe Biden",
          vicepresident: "Kamala Harris",
          housespeaker: "Vacant",
          chiefjustice: "John Roberts",
          gini: 39.4,
          hdi: 0.921,
          currency: "U.S. dollar",
          dateformat: "mm/dd/yyyy",
          drivingside: "right",
          callingcode: "+1",
          iso3166code: 'US',
          internettld: 'us',
          origin: [
            {
              nonHispanicOrLatino: 81.3,
              hispanicOrLatino: 18.7
            }
          ],
          religion: [{
            christianity: [{
              protestantism: 40,
              catholicism: 21,
              other: 2
            }],
            unaffiliated: 29,
            buddhism:1,
            hinduism: 1,
            islam: 1,
            judaism: 1,
            other: 2,
            unanswered: 2
          }],
          timezone: [{
            timezone: "	UTC−4 to −12, +10, +11",
            summer: "UTC−4 to −10[g]"
          }],
          independencefromGreatBritain: [{
            declaration: 'July 4, 1776',
            confederation: 'March 1, 1781',
            recognized: 'September 3, 1783',
            constitution: 'June 21, 1788',
            lastamendment: 'May 5, 1992'
          }],
          area: [{
            totalarea: 379674,
            water: 4.66,
            landarea: 3531905
          }],
          pop: [{
            twentytwoestimate: 333287557,
            twentycensus: 331449281,
            density: "87/sq mi"
          }],
          gdp: [{
            year: 2023,
            total: "$26.949 trillion",
            percapita: "$80412"
          }],
          legislature: [{
            congress: 'Congress',
            upperhouse: 'Senate',
            lowerhouse: 'House of Representatives'
          }],
          ethnicgroups: [
            {
              white: 61.6,
              black: 12.4,
              asian: 6,
              nativeamerican: 1.1,
              pacificislander: 0.2,
              twoormoreraces: 10.2,
              other: 8.4
            }
          ],
          region: [
            {
              state: [
                {
                  name: "Alabama",
                  abreviation: "AL",
                  capital: "Montgomery",
                  largest: "Huntsville",
                  admission: 'Dec 14,1819',
                  population: 5024279,
                  totalarea: 135767,
                  landarea: 131171,
                  waterarea:4597,
                  numberOfReps: 7,
                  electoralVotes: 9,
                  senators: 2,
                  hor: 7
                },
                {
                  name: "Alaska",
                  abreviation: "AK",
                  capital: 'Juneau',
                  largest: 'Anchorage',
                  admission: 'Jan 3, 1959',
                  population: 733391,
                  totalarea: 1723337,
                  landarea: 1477953,
                  waterarea: 245384,
                  numberOfReps: 1,
                  numberofcountyequivalents: 29,
                  electoralVotes: 3,
                  senators: 2,
                  hor: 1
                },
                {
                  name: "Arizona",
                  abreviation: "AZ",
                  capital: 'Phoenix',
                  largest: 'Phoenix',
                  admission: 'Fed 14, 1912',
                  population: 7151502,
                  totalarea: 295234,
                  landarea: 294207,
                  waterarea: 1026,
                  numberOfReps: 9,
                  numberofcountyequivalents: 15,
                  electoralVotes: 11,
                  senators: 2,
                  hor: 9
                },
                {
                  name: "Arkansas",
                  abreviation: "AR",
                  capital: 'Little Rock',
                  largest: 'Little Rock',
                  admission: 'Jun 15, 1836',
                  population: 3011524,
                  totalarea: 137732,
                  landarea: 134771,
                  waterarea: 2961,
                  numberOfReps: 4,
                  numberofcountyequivalents: 75,
                  electoralVotes: 6,
                  senators: 2,
                  hor:4
                },
                {
                  name: "California",
                  abreviation: "CA",
                  capital: 'Sacramento',
                  largest: 'Los Angeles',
                  admission: 'Sep 9, 1850',
                  population: 39538223,
                  totalarea: 423967,
                  landarea: 403466,
                  waterarea: 20501,
                  numberOfReps: 52,
                  numberofcountyequivalents: 58,
                  electoralVotes: 54,
                  senators: 2,
                  hor: 52
                },
                {
                  name: "Colorado",
                  abreviation: 'CO',
                  capital: 'Denver',
                  largest: 'Denver',
                  admission: 'Aug 1, 1876',
                  population: 5773714,
                  totalarea: 269601,
                  landarea: 268431,
                  waterarea: 1170,
                  numberOfReps: 8,
                  numberofcountyequivalents: 64,
                  electoralVotes: 10,
                  senators: 2,
                  hor: 8
                },
                {
                  name: "Delaware",
                  abreviation: 'DE',
                  capital: 'Dover',
                  largest: 'Wilmington',
                  admission: 'Dec 7, 1787',
                  population: 989948,
                  totalarea: 6446,
                  landarea: 5047,
                  waterarea: 1399,
                  numberOfReps: 1,
                  numberofcountyequivalents:3,
                  electoralVotes: 3,
                  senators: 2,
                  hor: 1
                },
                {
                  name: "Florida",
                  abreviation: 'FL',
                  capital: 'Tallahassee',
                  largest: 'Jacksonville',
                  admission: 'Mar 3, 1845',
                  population: 21538187,
                  totalarea: 170312,
                  landarea: 138887,
                  waterarea: 31424,
                  numberOfReps: 28,
                  numberofcountyequivalents: 67,
                  electoralVotes: 30,
                  senators: 2,
                  hor: 28
                },
                {
                  name: "Georgia",
                  abreviation: 'GA',
                  capital: 'Atlanta',
                  largest: 'Atlanta',
                  admission: 'Jan 2, 1788',
                  population: 10711908,
                  totalarea: 153910,
                  landarea: 148959,
                  waterarea: 4951,
                  numberOfReps: 14,
                  numberofcountyequivalents: 159,
                  electoralVotes: 16,
                  senators: 2,
                  hor: 14
                },
                {
                  name: "Hawaii",
                  abreviation: 'HI',
                  capital: 'Honolulu',
                  largest: 'Honolulu',
                  admission: 'Aug 21, 1959',
                  population: 1455271,
                  totalarea: 28313,
                  landarea: 16635,
                  waterarea: 11678,
                  numberOfReps: 2,
                  numberofcountyequivalents: 5,
                  electoralVotes: 4,
                  senators: 2,
                  hor: 2
                },
                {
                  name: "Idaho",
                  abreviation: 'ID',
                  capital: 'Boise',
                  largest: 'Boise',
                  admission: 'Jul 3, 1890',
                  population: 1839106,
                  totalarea: 216443,
                  landarea: 214045,
                  waterarea: 2398,
                  numberOfReps: 2,
                  numberofcountyequivalents: 44,
                  electoralVotes: 4,
                  senators: 2,
                  hor: 2
                },
                {
                  name: "Illinois",
                  abreviation: 'IL',
                  capital: 'Springfield',
                  largest: 'Chicago',
                  admission: 'Dec 3. 1818',
                  population: 12812508,
                  totalarea: 149995,
                  landarea: 143793,
                  waterarea: 6202,
                  numberOfReps: 17,
                  numberofcountyequivalents: 102,
                  electoralVotes: 19,
                  senators: 2,
                  hor: 17
                },
                {
                  name: "Indiana",
                  abreviation: 'IN',
                  capital: 'Indianapolis',
                  largest: 'Indianapolis',
                  admission: 'Dec 11, 1816',
                  population: 6785528,
                  totalarea: 94326,
                  landarea: 92789,
                  waterarea: 1537,
                  numberOfReps: 9,
                  numberofcountyequivalents: 92,
                  electoralVotes: 11,
                  senators: 2,
                  hor: 9
                },
                {
                  name: "Iowa",
                  abreviation: 'IA',
                  capital: 'Des Moines',
                  largest: 'Des Moines',
                  admission: 'Dec 28, 1846',
                  population: 3190369,
                  totalarea: 145746,
                  landarea: 144669,
                  waterarea: 1077,
                  numberOfReps: 4,
                  numberofcountyequivalents: 99,
                  electoralVotes: 6,
                  senators: 2,
                  hor: 4
                },
                {
                  name: "Kansas",
                  abreviation: 'KS',
                  capital: 'Topeka',
                  largest: 'Wichita',
                  admission: 'Jan 29, 1861',
                  population: 2937880,
                  totalarea: 213100,
                  landarea: 211754,
                  waterarea: 1346,
                  numberOfReps: 4,
                  numberofcountyequivalents: 105,
                  electoralVotes: 6,
                  senators: 2,
                  hor: 4
                },
                {
                  name: "Kentucky",
                  abreviation: 'KY',
                  capital: 'Frankfort',
                  largest: 'Louisville',
                  admission: 'Jun 1, 1792',
                  population: 4505836,
                  totalarea: 104656,
                  landarea: 102269,
                  waterarea: 2387,
                  numberOfReps: 6,
                  numberofcountyequivalents: 120,
                  electoralVotes: 8,
                  senators: 2,
                  hor: 6
                },
                {
                  name: "Loisiana",
                  abreviation: "LA",
                  capital: 'Baton Rouge',
                  largest: 'New Orleans',
                  admission: 'Apr 30, 1812',
                  population: 4657757,
                  totalarea: 135659,
                  landarea: 111898,
                  waterarea: 23761,
                  numberOfReps: 6,
                  numberofcountyequivalents: 64,
                  electoralVotes: 8,
                  senators: 2,
                  hor: 6
                },
                {
                  name: "Maine",
                  abreviation: "ME",
                  capital: 'Augusta',
                  largest: 'Portland',
                  admission: 'Mar 15, 1820',
                  population: 1362359,
                  totalarea: 91633,
                  landarea: 79883,
                  waterarea: 11750,
                  numberOfReps: 2,
                  numberofcountyequivalents: 16,
                  electoralVotes: 4,
                  senators: 2,
                  hor: 2
                },
                {
                  name: "Maryland",
                  abreviation: "MD",
                  capital: 'Annapolis',
                  largest: 'Baltimore',
                  admission: 'Feb 6, 1788',
                  population: 6177224,
                  totalarea: 32131,
                  landarea: 25142,
                  waterarea: 6990,
                  numberOfReps: 8,
                  numberofcountyequivalents: 23,
                  electoralVotes: 10,
                  senators: 2,
                  hor: 8
                },
                {
                  name: "Massachusetts",
                  abreviation: "MA",
                  capital: 'Boston',
                  largest: 'Boston',
                  admission: 'Feb 6, 1788',
                  population: 7028917,
                  totalarea: 27336,
                  landarea: 20202,
                  waterarea: 7134,
                  numberOfReps: 9,
                  numberofcountyequivalents: 14,
                  electoralVotes: 11,
                  senators: 2,
                  hor: 9
                },
                {
                  name: "Michigan",
                  abreviation: "MI",
                  capital: 'Lansing',
                  largest: 'Detroit',
                  admission: 'Jan 26, 1837',
                  population: 10077331,
                  totalarea: 250487,
                  landarea: 146435,
                  waterarea: 104052,
                  numberOfReps: 13,
                  numberofcountyequivalents: 83,
                  electoralVotes: 15,
                  senators: 2,
                  hor: 13
                },
                {
                  name: "Minnesota",
                  abreviation: "MN",
                  capital: 'Saint Paul',
                  largest: 'Minneapolis',
                  admission: 'May 11, 1858',
                  population: 5706494,
                  totalarea: 225163,
                  landarea: 206232,
                  waterarea: 18930,
                  numberOfReps: 8,
                  numberofcountyequivalents: 87,
                  electoralVotes: 10,
                  senators: 2,
                  hor: 8
                },
                {
                  name: "Mississippi",
                  abreviation: "MS",
                  capital: 'Jackson',
                  largest: 'Jackson',
                  admission: 'Dec 10, 1817',
                  population: 2961279,
                  totalarea: 125438,
                  landarea: 121531,
                  waterarea: 3907,
                  numberOfReps: 4,
                  numberofcountyequivalents: 82,
                  electoralVotes: 6,
                  senators: 2,
                  hor: 4
                },
                {
                  name: "Missouri",
                  abreviation: "MO",
                  capital: 'Jefferson City',
                  largest: 'Kansas City',
                  admission: 'Aug 10, 1821',
                  population: 6154913,
                  totalarea: 180540,
                  landarea: 178040,
                  waterarea: 2501,
                  numberOfReps: 8,
                  numberofcountyequivalents: 114,
                  electoralVotes: 10,
                  senators: 2,
                  hor: 8
                },
                {
                  name: "Montana",
                  abreviation: "MT",
                  capital: 'Helena',
                  largest: 'Billings',
                  admission: 'Nov 8, 1889',
                  population: 1082225,
                  totalarea: 380831,
                  landarea: 376962,
                  waterarea: 3869,
                  numberOfReps: 2,
                  numberofcountyequivalents: 56,
                  electoralVotes: 10,
                  senators: 2,
                  hor: 2
                },
                {
                  name: "Nebraska",
                  abreviation: "NV",
                  capital: 'Lincoln',
                  largest: 'Omaha',
                  admission: 'Mar 1, 1889',
                  population: 1961504,
                  totalarea: 200330,
                  landarea: 198974,
                  waterarea: 1356,
                  numberOfReps: 3,
                  numberofcountyequivalents: 93,
                  electoralVotes: 5,
                  senators: 2,
                  hor: 3
                },
                {
                  name: "Nevada",
                  abreviation: "NV",
                  capital: 'Carson City',
                  largest: 'Las Vegas',
                  admission: 'Oct 31, 1864',
                  population: 3104614,
                  totalarea: 286380,
                  landarea: 284332,
                  waterarea: 2048,
                  numberOfReps: 4,
                  numberofcountyequivalents: 16,
                  electoralVotes: 6,
                  senators: 2,
                  hor: 4
                },
                {
                  name: "New Hampshire",
                  abreviation: "NH",
                  capital: 'Concord',
                  largest: 'Manchester',
                  admission: 'Jun 21, 1788',
                  population: 1377529,
                  totalarea: 24214,
                  landarea: 23187,
                  waterarea: 1027,
                  numberOfReps: 2,
                  numberofcountyequivalents: 10,
                  electoralVotes: 4,
                  senators: 2,
                  hor: 2
                },
                {
                  name: "New Jersey",
                  abreviation: "NJ",
                  capital: ' ',
                  largest: ' ',
                  admission: ' ',
                  population: 0,
                  totalarea: 0,
                  landarea: 0,
                  waterarea: 0,
                  numberOfReps: 0,
                  numberofcountyequivalents: 10,
                  electoralVotes: 14,
                  senators: 2,
                  hor: 12
                },
                {
                  name: "New Mexico",
                  abreviation: "NM",
                  capital: 'Santa Fe',
                  largest: 'Albuquerque',
                  admission: 'Jan 6, 1912',
                  population: 2117522,
                  totalarea: 314917,
                  landarea: 314161,
                  waterarea: 757,
                  numberOfReps: 3,
                  numberofcountyequivalents: 33,
                  electoralVotes: 5,
                  senators: 2,
                  hor: 3
                },
                {
                  name: "New York",
                  abreviation: "NY",
                  capital: 'Albany',
                  largest: 'New York City',
                  admission: 'Jul 26, 1788',
                  population: 20201249,
                  totalarea: 141297,
                  landarea: 122057,
                  waterarea: 19240,
                  numberOfReps: 26,
                  numberofcountyequivalents: 62,
                  electoralVotes: 28,
                  senators: 2,
                  hor: 26
                },
                {
                  name: "North Carolina",
                  abreviation: "NC",
                  capital: 'Raleigh',
                  largest: 'Charlotte',
                  admission: 'Nov 21, 1789',
                  population: 10439388,
                  totalarea: 139391,
                  landarea: 125920,
                  waterarea: 13471,
                  numberOfReps: 14,
                  numberofcountyequivalents: 100,
                  electoralVotes: 16,
                  senators: 2,
                  hor: 14
                },
                {
                  name: "North Dakota",
                  abreviation: "ND",
                  capital: 'Bismarck',
                  largest: 'Fargo',
                  admission: 'Nov 2, 1889',
                  population: 779094,
                  totalarea: 183108,
                  landarea: 178711,
                  waterarea: 4397,
                  numberOfReps: 1,
                  numberofcountyequivalents: 53,
                  electoralVotes: 3,
                  senators: 2,
                  hor: 1
                },
                {
                  name: "Ohio",
                  abreviation: "OH",
                  capital: 'Columbus',
                  largest: 'Columbus',
                  admission: 'Mar 1, 1803',
                  population: 11799448,
                  totalarea: 116098,
                  landarea: 105829,
                  waterarea: 10269,
                  numberOfReps: 15,
                  numberofcountyequivalents: 88,
                  electoralVotes: 17,
                  senators: 2,
                  hor: 15
                },
                {
                  name: "Oklahoma",
                  abreviation: "OK",
                  capital: 'Oklahoma City',
                  largest: 'Oklahoma City',
                  admission: 'Nov 16, 1907',
                  population: 3959353,
                  totalarea: 181037,
                  landarea: 177660,
                  waterarea: 3377,
                  numberOfReps: 5,
                  numberofcountyequivalents: 77,
                  electoralVotes: 7,
                  senators: 2,
                  hor: 5
                },
                {
                  name: "Oregon",
                  abreviation: "OR",
                  capital: 'Salem',
                  largest: 'Portland',
                  admission: 'Feb 14, 1859',
                  population: 4237256,
                  totalarea: 254799,
                  landarea: 248608,
                  waterarea: 6191,
                  numberOfReps: 6,
                  numberofcountyequivalents: 36,
                  electoralVotes: 8,
                  senators: 2,
                  hor: 6
                },
                {
                  name: "Pennsylvania",
                  abreviation: "PA",
                  capital: 'Harrisburg',
                  largest: 'Philadelphia',
                  admission: 'Dec 12, 1787',
                  population: 13002700,
                  totalarea: 119280,
                  landarea: 115883,
                  waterarea: 3397,
                  numberOfReps: 17,
                  numberofcountyequivalents: 67,
                  electoralVotes: 19,
                  senators: 2,
                  hor: 17
                },
                {
                  name: "Rhode Island",
                  abreviation: "RI",
                  capital: 'Providence',
                  largest: 'May 29, 1788',
                  admission: 'May 29, 1790',
                  population: 1097379,
                  totalarea: 4001,
                  landarea: 2678,
                  waterarea: 1324,
                  numberOfReps: 2,
                  numberofcountyequivalents: 5,
                  electoralVotes: 4,
                  senators: 2,
                  hor: 2
                },
                {
                  name: "South Carolina",
                  abreviation: "SC",
                  capital: 'Columbia',
                  largest: 'Charleston',
                  admission: 'May 23, 1788',
                  population: 5118425,
                  totalarea: 82933,
                  landarea: 77857,
                  waterarea: 5076,
                  numberOfReps: 7,
                  numberofcountyequivalents: 46,
                  electoralVotes: 9,
                  senators: 2,
                  hor: 7
                },
                {
                  name: "South Dakota",
                  abreviation: "SD",
                  capital: 'Pierre',
                  largest: 'Sioux Falls',
                  admission: 'Nov 2, 1889',
                  population: 886667,
                  totalarea: 199729,
                  landarea: 196350,
                  waterarea: 3379,
                  numberOfReps: 1,
                  numberofcountyequivalents: 66,
                  electoralVotes: 3,
                  senators: 2,
                  hor: 1
                },
                {
                  name: "Tennessee",
                  abreviation: "TN",
                  capital: 'Nashville',
                  largest: 'Nashville',
                  admission: 'Jun 1, 1796',
                  population: 6910840,
                  totalarea: 109729,
                  landarea: 106798,
                  waterarea: 2355,
                  numberOfReps: 9,
                  numberofcountyequivalents: 95,
                  electoralVotes: 11,
                  senators: 2,
                  hor: 9
                },
                {
                  name: "Texas",
                  abreviation: "TX",
                  capital: 'Austin',
                  largest: 'Houston',
                  admission: 'Dec 29,  1845',
                  population: 29145505,
                  totalarea: 695662,
                  landarea: 676587,
                  waterarea: 19075,
                  numberOfReps: 38,
                  numberofcountyequivalents: 254,
                  electoralVotes: 40,
                  senators: 2,
                  hor: 38
                },
                {
                  name: "Utah",
                  abreviation: "UT",
                  capital: 'Salt Lake City',
                  largest: 'Salt Lake City',
                  admission: 'Jan 4, 1896',
                  population: 3271616,
                  totalarea: 219882,
                  landarea: 212818,
                  waterarea: 7064,
                  numberOfReps: 4,
                  numberofcountyequivalents: 29,
                  electoralVotes: 6,
                  senators: 2,
                  hor: 4
                },
                {
                  name: "Vermont",
                  abreviation: "VT",
                  capital: 'Montpelier',
                  largest: 'Burlington',
                  admission: 'Mar 4, 1791',
                  population: 643077,
                  totalarea: 24906,
                  landarea: 23871,
                  waterarea: 1035,
                  numberOfReps: 1,
                  numberofcountyequivalents: 14,
                  electoralVotes: 3,
                  senators: 2,
                  hor: 1
                },
                {
                  name: "Virginia",
                  abreviation: "VA",
                  capital: 'Richmond',
                  largest: 'Virginia Beach',
                  admission: 'Jun 25,  1788',
                  population: 8631393,
                  totalarea: 110787,
                  landarea: 102279,
                  waterarea: 8508,
                  numberOfReps: 11,
                  numberofcountyequivalents: 95,
                  electoralVotes: 13,
                  senators: 2,
                  hor: 11
                },
                {
                  name: "Washington",
                  abreviation: "WA",
                  capital: 'Olympia',
                  largest: 'Seattle',
                  admission: 'Nov 11, 1889',
                  population: 7705281,
                  totalarea: 184661,
                  landarea: 172119,
                  waterarea: 12542,
                  numberOfReps: 10,
                  numberofcountyequivalents: 39,
                  electoralVotes: 12,
                  senators: 2,
                  hor: 10
                },
                {
                  name: "West Virginia",
                  abreviation: "WV",
                  capital: 'Charleston',
                  largest: 'Charleston',
                  admission: 'Jun 20, 1863',
                  population: 1793716,
                  totalarea: 62756,
                  landarea: 62259,
                  waterarea: 497,
                  numberOfReps: 2,
                  numberofcountyequivalents: 55,
                  electoralVotes: 4,
                  senators: 2,
                  hor: 2
                },
                {
                  name: "Wisconsin",
                  abreviation: 'WI',
                  capital: 'Madison',
                  largest: 'Milwaukee',
                  admission: 'May 29, 1848',
                  population: 5893718,
                  totalarea: 169635,
                  landarea: 140268,
                  waterarea: 29367,
                  numberOfReps: 8,
                  numberofcountyequivalents: 72,
                  electoralVotes: 10,
                  senators: 2,
                  hor: 8
                },
                {
                  name: 'Wyoming',
                  abreviation: 'WY',
                  capital: 'Cheyenne',
                  largest: 'Cheyenne',
                  admission: 'Jun 10, 1890',
                  population: 576851,
                  totalarea: 253335,
                  landarea: 251470,
                  waterarea: 1864,
                  numberOfReps: 1,
                  numberofcountyequivalents: 23,
                  electoralVotes: 3,
                  senators: 2,
                  hor: 1
                }, 
              ],
              district: [
                {
                  name: "District of Columbia",
                  abreviation: 'DC',
                  established: "Jul 16, 1790",
                  population: 689545,
                  totalarea: 176,
                  landarea: 158,
                  waterarea: 18,
                  numberofreps: 1,
                  electoralVotes: 3,
                  hornvm: 1
                }
              ],
              territory: [
                {
                  name: 'American Samoa',
                  abreviation: 'AS',
                  capital: 'Pago Pago',
                  acquired: 1900,
                  TerritorialStatus: 'Unincorporated unorganized',
                  population: 49710,
                  totalarea: 1505,
                  landarea: 198,
                  waterarea: 1307,
                  numberofreps: 1,
                  hornvm: 1
                },
                {
                  name: 'Guam',
                  abreviation: 'GU',
                  capital: 'Hagatna',
                  acquired: 1899,
                  TerritorialStatus: 'Unincorporated organized',
                  population: 153836,
                  totalarea: 1478,
                  landarea: 543,
                  waterarea: 935,
                  numberofreps: 1,
                  hornvm: 1
                },
                {
                  name: 'Northern Mariana Islands',
                  abreviation: 'MP',
                  capital: 'Saipan',
                  acquired: 1986,
                  TerritorialStatus: 'Unincorporated organized',
                  population: 47329,
                  totalarea: 5117,
                  landarea: 472,
                  waterarea: 4644,
                  numberofreps: 1,
                  hornvm: 1
                },
                {
                  name: 'Puerto Rico',
                  abreviation: 'PR',
                  capital: 'San Juan',
                  acquired: 1899,
                  TerritorialStatus: 'Unincorporated organized',
                  population: 3285874,
                  totalarea: 13791,
                  landarea: 8868,
                  waterarea: 4924,
                  numberofreps: 1,
                  hornvm: 1
                },
                {
                  name: 'U.S. Virgin Islands',
                  abreviation: 'VI',
                  capital: 'Charlotte Amalie',
                  acquired: 1917,
                  TerritorialStatus: 'Unincorporated organized',
                  population: 87146,
                  totalarea: 1898,
                  landarea: 348,
                  waterarea: 1550,
                  numberofreps: 1,
                  hornvm: 1
                }
              ],
              uninhabitedterritories: [
                {
                  name: 'Baker Island',
                  acquired: 1856,
                  status: 'Unincorporated, unorganized',
                  landarea: 2.2
                },
                {
                  name: 'Midway Atoll',
                  acquired: 1867,
                  status: 'Unincorporated, unorganized',
                  landarea: 7.8
                },
                {
                  name: 'Navassa Island',
                  acquired: 1858,
                  status: 'Unincorporated, unorganized',
                  landarea: 7.8
                },
                {
                  name: 'Wake Island',
                  acquired: 1899,
                  status: 'Unincorporated, unorganized',
                  landarea: 6.5
                },
                {
                  name: 'Jarvis Island',
                  acquired: 1856,
                  status: 'Unincorporated, unorganized',
                  landarea: 5.7
                },
                {
                  name: 'Palmyra Atoll',
                  acquired: 1898,
                  status: 'Unincorporated, unorganized',
                  landarea: 3.9
                },
                {
                  name: 'Johnston Atoll',
                  acquired: 1859,
                  status: 'Unincorporated, unorganized',
                  landarea: 2.6
                },
                {
                  name: 'Howland Island',
                  acquired: 1858,
                  status: 'Unincorporated, unorganized',
                  landarea: 1.6
                },
                {
                  name: 'Kingman Reef',
                  acquired: 1860,
                  status: 'Unincorporated, unorganized',
                  landarea: 0.01
                }
              ],
              county: [
                { 
                    county: 'Autauga',
                    state: 'Alabama',
                    population: 58805,
                    Areami2: 594.44,
                },
                { 
                    county: 'Baldwin',
                    state: 'Alabama',
                    population: 231767,
                    Areami2: 1589.78,
                },
                { 
                    county: 'Barbour',
                    state: 'Alabama',
                    population: 25223,
                    Areami2: 884.88,
                },
                { 
                    county: 'Bibb',
                    state: 'Alabama',
                    population: 22293,
                    Areami2: 622.58,
                },
                { 
                    county: 'Blount',
                    state: 'Alabama',
                    population: 59134,
                    Areami2: 644.78,
                },
                { 
                    county: 'Bullock',
                    state: 'Alabama',
                    population: 10357,
                    Areami2: 622.80,
                },
                { 
                    county: 'Butler',
                    state: 'Alabama',
                    population: 19051,
                    Areami2: 776.83,
                },
                { 
                    county: 'Calhoun',
                    state: 'Alabama',
                    population: 116441,
                    Areami2: 605.87,
                },
                { 
                    county: 'Chambers',
                    state: 'Alabama',
                    population: 34772,
                    Areami2: 596.53,
                },
                { 
                    county: 'Cherokee',
                    state: 'Alabama',
                    population: 24971,
                    Areami2: 553.70,
                },
                { 
                    county: 'Chilton',
                    state: 'Alabama',
                    population: 45014,
                    Areami2: 692.85,
                },
                { 
                    county: 'Choctaw',
                    state: 'Alabama',
                    population: 12665,
                    Areami2: 913.50,
                },
                { 
                    county: 'Clarke',
                    state: 'Alabama',
                    population: 23087,
                    Areami2: 1238.46,
                },
                { 
                    county: 'Clay',
                    state: 'Alabama',
                    population: 14236,
                    Areami2: 603.96,
                },
                { 
                    county: 'Cleburne',
                    state: 'Alabama',
                    population: 15056,
                    Areami2: 560.10,
                },
                { 
                    county: 'Coffee',
                    state: 'Alabama',
                    population: 53465,
                    Areami2: 678.97,
                },
                { 
                    county: 'Colbert',
                    state: 'Alabama',
                    population: 57227,
                    Areami2: 592.62,
                },
                { 
                    county: 'Conecuh',
                    state: 'Alabama',
                    population: 11597,
                    Areami2: 850.16,
                },
                { 
                    county: 'Coosa',
                    state: 'Alabama',
                    population: 10387,
                    Areami2: 650.93,
                },
                { 
                    county: 'Covington',
                    state: 'Alabama',
                    population: 37570,
                    Areami2: 1030.46,
                },
                { 
                    county: 'Crenshaw',
                    state: 'Alabama',
                    population: 13194,
                    Areami2: 608.84,
                },
                { 
                    county: 'Cullman',
                    state: 'Alabama',
                    population: 87866,
                    Areami2: 734.84,
                },
                { 
                    county: 'Dale',
                    state: 'Alabama',
                    population: 87866,
                    Areami2: 734.84,
                },
                { 
                    county: 'Dallas',
                    state: 'Alabama',
                    population: 38462,
                    Areami2: 978.69,
                },
                { 
                    county: 'DeKalb',
                    state: 'Alabama',
                    population: 71608,
                    Areami2: 77.09,
                },
                { 
                    county: 'Elmore',
                    state: 'Alabama',
                    population: 87977,
                    Areami2: 618.48,
                },
                { 
                    county: 'Escambia',
                    state: 'Alabama',
                    population: 36757,
                    Areami2: 945.08,
                },
                { 
                    county: 'Etowah',
                    state: 'Alabama',
                    population: 103436,
                    Areami2: 534.99,
                },
                { 
                    county: 'Fayette',
                    state: 'Alabama',
                    population: 16321,
                    Areami2: 627.66,
                },
                { 
                    county: 'Franklin',
                    state: 'Alabama',
                    population: 32113,
                    Areami2: 633.82,
                },
                { 
                    county: 'Geneva',
                    state: 'Alabama',
                    population: 26659,
                    Areami2: 574.41,
                },
                { 
                    county: 'Greene',
                    state: 'Alabama',
                    population: 7730,
                    Areami2: 647.11,
                },
                { 
                    county: 'Hale',
                    state: 'Alabama',
                    population: 14785,
                    Areami2: 643.94,
                },
                { 
                    county: 'Henry',
                    state: 'Alabama',
                    population: 14785,
                    Areami2: 643.94,
                },
                { 
                    county: 'Houston',
                    state: 'Alabama',
                    population: 107202,
                    Areami2: 579.82,
                },
                { 
                    county: 'Jackson',
                    state: 'Alabama',
                    population: 52579,
                    Areami2: 1077.87,
                },
                { 
                    county: 'Jefferson',
                    state: 'Alabama',
                    population: 674721,
                    Areami2: 1111.28,
                },
                { 
                    county: 'Lamar',
                    state: 'Alabama',
                    population: 13972,
                    Areami2: 604.85,
                },
                { 
                    county: 'Lauderdale',
                    state: 'Alabama',
                    population: 93564,
                    Areami2: 667.70,
                },
                { 
                    county: 'Lawrence',
                    state: 'Alabama',
                    population: 33073,
                    Areami2: 690.68,
                },
                { 
                    county: 'Lee',
                    state: 'Alabama',
                    population: 174241,
                    Areami2: 607.54,
                },
                { 
                    county: 'Limestone',
                    state: 'Alabama',
                    population: 103570,
                    Areami2: 559.94,
                },
                { 
                    county: 'Lowndes',
                    state: 'Alabama',
                    population: 10311,
                    Areami2: 715.91,
                },
                { 
                    county: 'Macon',
                    state: 'Alabama',
                    population: 19532,
                    Areami2: 608.89,
                },
                { 
                    county: 'Madison',
                    state: 'Alabama',
                    population: 388153,
                    Areami2: 801.59,
                },
                { 
                    county: 'Marengo',
                    state: 'Alabama',
                    population: 19323,
                    Areami2: 976.88,
                },
                { 
                    county: 'Marion',
                    state: 'Alabama',
                    population: 29341,
                    Areami2: 742.29,
                },
                { 
                    county: 'Marshall',
                    state: 'Alabama',
                    population: 97612,
                    Areami2: 565.84,
                },
                { 
                    county: 'Mobile',
                    state: 'Alabama',
                    population: 414809,
                    Areami2: 1229.44,
                },
                { 
                    county: 'Monroe',
                    state: 'Alabama',
                    population: 19772,
                    Areami2: 1025.67,
                },
                { 
                    county: 'Montgomery',
                    state: 'Alabama',
                    population: 228954,
                    Areami2: 784.25,
                },
                { 
                    county: 'Morgan',
                    state: 'Alabama',
                    population: 123421,
                    Areami2: 579.34,
                },
                { 
                    county: 'Perry',
                    state: 'Alabama',
                    population: 8511,
                    Areami2: 719.66,
                },
                { 
                    county: 'Pickens',
                    state: 'Alabama',
                    population: 19123,
                    Areami2: 881.41,
                },
                { 
                    county: 'Pike',
                    state: 'Alabama',
                    population: 33009,
                    Areami2: 672.09,
                },
                { 
                    county: 'Randolph',
                    state: 'Alabama',
                    population: 21967,
                    Areami2: 580.55,
                },
                { 
                    county: 'Russell',
                    state: 'Alabama',
                    population: 59183,
                    Areami2: 641.14,
                },
                { 
                    county: 'St. Clair',
                    state: 'Alabama',
                    population: 91103,
                    Areami2: 631.90,
                },
                { 
                    county: 'Shelby',
                    state: 'Alabama',
                    population: 223024,
                    Areami2: 784.93,
                },
                { 
                    county: 'Sumter',
                    state: 'Alabama',
                    population: 12345,
                    Areami2: 903.89,
                },
                { 
                    county: 'Talladega',
                    state: 'Alabama',
                    population: 82149,
                    Areami2: 736.78,
                },
                { 
                    county: 'Tallapoosa',
                    state: 'Alabama',
                    population: 41311,
                    Areami2: 716.52,
                },
                { 
                    county: 'Tuscaloosa',
                    state: 'Alabama',
                    population: 227036,
                    Areami2: 1321.75,
                },
                { 
                    county: 'Walker',
                    state: 'Alabama',
                    population: 65342,
                    Areami2: 791.19,
                },
                { 
                    county: 'Washington',
                    state: 'Alabama',
                    population: 15388,
                    Areami2: 1080.21,
                },
                { 
                    county: 'Wilcox',
                    state: 'Alabama',
                    population: 10600,
                    Areami2: 88.50,
                },
                { 
                    county: 'Winston',
                    state: 'Alabama',
                    population: 23540,
                    Areami2: 612.98,
                },
                { 
                    county: 'Aleutians East Borough',
                    state: 'Alaska',
                    population: 3420,
                    Areami2: 6985,
                },
                { 
                    county: 'Aleutians West Census Area',
                    state: 'Alaska',
                    population: 5232,
                    Areami2: 4393,
                },
                { 
                    county: 'Anchorage, Municipality',
                    state: 'Alaska',
                    population: 291247,
                    Areami2: 1707,
                },
                { 
                    county: 'Bethel Census Area',
                    state: 'Alaska',
                    population: 18666,
                    Areami2: 40627,
                },
                { 
                    county: 'Bristol Bay Borough',
                    state: 'Alaska',
                    population: 844,
                    Areami2: 482,
                },
                { 
                    county: 'Chugach Census Area',
                    state: 'Alaska',
                    population: 7102,
                    Areami2: 9530,
                },
                { 
                    county: 'Copper River Census Area',
                    state: 'Alaska',
                    population: 2617,
                    Areami2: 24692,
                },
                { 
                    county: 'Denali Borough',
                    state: 'Alaska',
                    population: 1619,
                    Areami2: 12641,
                },
                { 
                    county: 'Dillingham Census Area',
                    state: 'Alaska',
                    population: 4857,
                    Areami2: 18334,
                },
                { 
                    county: 'Fairbanks North Star Borough',
                    state: 'Alaska',
                    population: 95655,
                    Areami2: 7335,
                },
                { 
                    county: 'Haines Borough',
                    state: 'Alaska',
                    population: 2080,
                    Areami2: 2343,
                },
                { 
                    county: 'Hoonah-Angoon Census Area',
                    state: 'Alaska',
                    population: 2365,
                    Areami2: 6555,
                },
                { 
                    county: 'Juneau, City and Borough',
                    state: 'Alaska',
                    population: 32255,
                    Areami2: 2704,
                },
                { 
                    county: 'Kenai Peninsula Borough',
                    state: 'Alaska',
                    population: 58799,
                    Areami2: 16017,
                },
                { 
                    county: 'Ketchikan Gateway borough',
                    state: 'Alaska',
                    population: 13948,
                    Areami2: 4857,
                },
                { 
                    county: 'Kodiak Island borough',
                    state: 'Alaska',
                    population: 13101,
                    Areami2: 6689,
                },
                { 
                    county: 'Kusilvak Census Area',
                    state: 'Alaska',
                    population: 8368,
                    Areami2: 17077,
                },
                { 
                    county: 'Lake and Peninsula Borough',
                    state: 'Alaska',
                    population: 1476,
                    Areami2: 23832,
                },
                { 
                    county: 'Matanuska-Susitna Borough',
                    state: 'Alaska',
                    population: 107081,
                    Areami2: 24707,
                },
                { 
                    county: 'Nome Census Area',
                    state: 'Alaska',
                    population: 10046,
                    Areami2: 22969,
                },
                { 
                    county: 'North Slope Borough',
                    state: 'Alaska',
                    population: 11031,
                    Areami2: 88824,
                },
                { 
                    county: 'Northwest Arctic Borough',
                    state: 'Alaska',
                    population: 7793,
                    Areami2: 35663,
                },
                { 
                    county: 'Petersburg Borough',
                    state: 'Alaska',
                    population: 3398,
                    Areami2: 2901,
                },
                { 
                    county: 'Prince of Wales - Hyder Census Area',
                    state: 'Alaska',
                    population: 5753,
                    Areami2: 5268,
                },
                { 
                    county: 'Sitka, City and borough',
                    state: 'Alaska',
                    population: 8458,
                    Areami2: 2870,
                },
                { 
                    county: 'Skagway, Minicipality',
                    state: 'Alaska',
                    population: 1240,
                    Areami2: 434,
                },
                { 
                    county: 'Southeast Fairbanks Census Area',
                    state: 'Alaska',
                    population: 6808,
                    Areami2: 24831,
                },
                { 
                    county: 'Wrangell, City and borough',
                    state: 'Alaska',
                    population: 2127,
                    Areami2: 2556,
                },
                { 
                    county: 'Yakutat, City and borough',
                    state: 'Alaska',
                    population: 662,
                    Areami2: 7623,
                },
                { 
                    county: 'Yukton-Koyukuk Census Area',
                    state: 'Alaska',
                    population: 5343,
                    Areami2: 145576,
                },
                { 
                    county: 'Yukton-Koyukuk Census Area',
                    state: 'Alaska',
                    population: 5343,
                    Areami2: 145576,
                },
              ]
            }
          ],
          economysystems: ['Traditional', 'Command', 'Centrally Planned', 'Market', 'Mixed'],
          economicsector: [
            'Mining', 'Utilities', 'Construction', 'Manufacturing', 'Wholesale trade',
            'Retail trade', 'Transportation and warehousing', 'Information', 'Finance and insurance',
            'Real estate and rental and leasing', 'Professional, scientific, and technical services',
            'Management of companies and enterprises', 'Administrative and support and waste management and remediation service',
            'Educational services', 'Health care and social assistance', 'arts, entertainment, and recreation', 'accommodation and food services',
            'other services (except public administration)']
        }],
        economy: [
            {year: 1980,
                gdpib: 2857.3,
                gdppc: 12552.9,
                gdpibnom: 2857.3,
                gdppcibnom: 12552.9,
                 },
            {year: 1981 },
            {year: 1982 },
            {year: 1983 },
            {year: 1984 },
        ]
    },
  ]

export default Datas;